name: Java CI with Maven

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: maven
      - name: create settings file
        run:
          echo "access_token=${{ secrets.TOKEN }}" > ${{ org.github.workspace }}/src/test/resources/env.properties
      - name: Build with Maven
        run: mvn -B package --file pom.xml
